---
components:
  schemas: 
    Device: 
      type: object
      description: |
        This entity contains a description of the state of a Device. This entity is associated with the vertical segments of  smart cities and related IoT applications.
        This data model has been partially developed based on the "Device" data model available on the SmartDataModels database.
        It is an extension of the data model and introduces the following changes:
        - Addition of the field "dateObserved" to record the timestamp of the entry.
        - Required fields has been reduced to only "id", "type" and "dateObserved".
        
      allOf:
        - $ref: "https://raw.githubusercontent.com/AlticeLabsProjects/live-data-sdm/main/dataModel.Device/Device/model.yaml#/Device"
      properties:
        dateObserved:
          description: Last reported time of observation.
          format: date-time
          type: string
          x-ngsi:
            model: https://schema.org/DateTime
            type: Property
      required:
        - dateObserved

info:
  description:  |
    An apparatus (hardware + software + firmware) intended to accomplish a particular task (sensing the environment, actuating, etc.).

  title: Device
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - Device
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Device/Device/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Device/Device/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld