---
components:
  schemas: 
    ParkingSpot:
      type: object
      description: |
        This entity contains a description of the state of a parking spot. This entity is associated with the vertical segments of  smart cities and related IoT applications.
        This data model has been partially developed based on the "ParkingSpot" data model available on the SmartDataModels database.
        It is an extension of the data model and introduces the following changes:
        - Addition of the field "dateObserved" to register the timestamp of entry.
        - Required fields has been reduced to "id", "type" and "dateObserved".
        
      allOf:
        - $ref: "https://raw.githubusercontent.com/AlticeLabsProjects/live-data-sdm/main/dataModel.Parking/ParkingSpot/model.yaml#/ParkingSpot"

      properties:
        dateObserved:
          description: Last reported time of observation.
          format: date-time
          type: string
          x-ngsi:
            model: https://schema.org/DateTime
            type: Property
      required:
        - dateObserved

info:
  description: |
    An extended observation of the state of a parking spot a certain place and time, based on the SmartDataModel ParkingSpot
  title: ParkingSpot
  version: "0.0.1"

openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system."
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - ParkingSpot
            type: string
      responses: 
        "200":
          description: OK
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Parking/ParkingSpot/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Parking/ParkingSpot/examples/example-normalized.jsonld"
      tags: 
        - ngsi-ld

tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
