---
components:
  schemas: 
    WeatherForecast: 
      $ref: "https://smart-data-models.github.io/dataModel.Weather/WeatherForecast/model.yaml#/WeatherForecast"
      type: object
      description: |
        This entity contains a description of a weather forecast over time. This entity is associated with the vertical segments of  smart cities and related IoT applications.
        This data model has been partially developed based on the "WeatherForecast" data model available on the SmartDataModels database which has been developed with mobile operators and the GSMA.
        It is an extension of the data model and introduces the following changes:
        - The required field `location` is no longer considered required.
        - `windType` is an additional field added.
        

      allOf:
          - $ref: "https://raw.githubusercontent.com/AlticeLabsProjects/live-data-sdm/main/dataModel.Weather/WeatherForecast/model.yaml#/WeatherForecast"
  
      properties:
        windType:
        x-ngsi:
          model: http//schema.org/Text
          type: "Property"
        type: string
        description: ""

info:
  description:  |
    A harmonised description of a Weather Forecast
  title: WeatherForecast
  version: "0.0.3"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - WeatherForecast
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Weather/WeatherForecast/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Weather/WeatherForecast/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
